language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '12'
  - '10'
  - '9'
  - '8'
install:
  - npm install
script:
  - npm run travis
after_script:
  - npx codecov
  - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
